defaults:
 - _self_
 - model: my_model/adapt_binary
 - optim: sgd
 - data: icdar
 - logger: mlflow
 - trainer: trainer
 - callbacks: checkpoint
 - losses: icdar
 
exp_name: ??
data:
  num_workers: "num_cpus"
  image_size: 640
  shrink_ratio: 0.4
  min_thresh: 0.3
  max_thresh: 0.7
  

work_dir: ${hydra:runtime.cwd}
log_dir: logs/runs/${exp_name}/${now:%H-%M-%S}
data_dir: ${work_dir}/datasets/
hydra:
    # output paths for hydra logs
    run:
        dir: ${log_dir}
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}

tokenization:
  bert-base-uncased

viz: False